#!/bin/bash

# Check if the filename argument was provided
if [ -z "$1" ]; then
	echo "Usage: exec {filename}"
	exit 1
fi

# Set the file permissions to 700 for exec files
chmod 700 $1

# Give feedback on completion
echo "File $1 given 700 permissions"
